### ISSUE TITLE
Sometimes multiple sessions are created

### ISSUE THREAD

**Issue by nikitos** [unikmhz/npui#7]
So this leads to an error

```
[Thu Aug 07 13:41:42 2014] [error] [client 192.168.101.107] mod_wsgi (pid=11300): Exception occurred processing WSGI script '/var/lib/netprofile/np/npdc.wsgi'.
[Thu Aug 07 13:41:42 2014] [error] [client 192.168.101.107] Traceback (most recent call last):
[Thu Aug 07 13:41:42 2014] [error] [client 192.168.101.107]   File "/var/lib/netprofile/np/lib/python3.2/site-packages/repoze.tm2-2.0-py3.2.egg/repoze/tm/__init__.py", line 58, in __call__
[Thu Aug 07 13:41:42 2014] [error] [client 192.168.101.107]     reraise(type_, value, tb)
[Thu Aug 07 13:41:42 2014] [error] [client 192.168.101.107]   File "/var/lib/netprofile/np/lib/python3.2/site-packages/repoze.tm2-2.0-py3.2.egg/repoze/tm/__init__.py", line 13, in reraise
[Thu Aug 07 13:41:42 2014] [error] [client 192.168.101.107]     raise value
[Thu Aug 07 13:41:42 2014] [error] [client 192.168.101.107]   File "/var/lib/netprofile/np/lib/python3.2/site-packages/repoze.tm2-2.0-py3.2.egg/repoze/tm/__init__.py", line 51, in __call__
[Thu Aug 07 13:41:42 2014] [error] [client 192.168.101.107]     for chunk in self.application(environ, save_status_and_headers):
[Thu Aug 07 13:41:42 2014] [error] [client 192.168.101.107]   File "/var/lib/netprofile/np/lib/python3.2/site-packages/pyramid-1.5a2-py3.2.egg/pyramid/router.py", line 272, in __call__
[Thu Aug 07 13:41:42 2014] [error] [client 192.168.101.107]     response = self.invoke_subrequest(request, use_tweens=True)
[Thu Aug 07 13:41:42 2014] [error] [client 192.168.101.107]   File "/var/lib/netprofile/np/lib/python3.2/site-packages/pyramid-1.5a2-py3.2.egg/pyramid/router.py", line 247, in invoke_subrequest
[Thu Aug 07 13:41:42 2014] [error] [client 192.168.101.107]     response = handle_request(request)
[Thu Aug 07 13:41:42 2014] [error] [client 192.168.101.107]   File "/var/lib/netprofile/np/lib/python3.2/site-packages/pyramid_debugtoolbar-1.0.9-py3.2.egg/pyramid_debugtoolbar/toolbar.py", line 141, in toolbar_tween
[Thu Aug 07 13:41:42 2014] [error] [client 192.168.101.107]     return handler(request)
[Thu Aug 07 13:41:42 2014] [error] [client 192.168.101.107]   File "/var/lib/netprofile/np/lib/python3.2/site-packages/pyramid-1.5a2-py3.2.egg/pyramid/tweens.py", line 21, in excview_tween
[Thu Aug 07 13:41:42 2014] [error] [client 192.168.101.107]     response = handler(request)
[Thu Aug 07 13:41:42 2014] [error] [client 192.168.101.107]   File "/var/lib/netprofile/np/lib/python3.2/site-packages/pyramid-1.5a2-py3.2.egg/pyramid/router.py", line 137, in handle_request
[Thu Aug 07 13:41:42 2014] [error] [client 192.168.101.107]     has_listeners and notify(ContextFound(request))
[Thu Aug 07 13:41:42 2014] [error] [client 192.168.101.107]   File "/var/lib/netprofile/np/lib/python3.2/site-packages/pyramid-1.5a2-py3.2.egg/pyramid/registry.py", line 74, in notify
[Thu Aug 07 13:41:42 2014] [error] [client 192.168.101.107]     [ _ for _ in self.subscribers(events, None) ]
[Thu Aug 07 13:41:42 2014] [error] [client 192.168.101.107]   File "/var/lib/netprofile/np/lib/python3.2/site-packages/zope.interface-4.0.5-py3.2-linux-i686.egg/zope/interface/registry.py", line 323, in subscribers
[Thu Aug 07 13:41:42 2014] [error] [client 192.168.101.107]     return self.adapters.subscribers(objects, provided)
[Thu Aug 07 13:41:42 2014] [error] [client 192.168.101.107]   File "/var/lib/netprofile/np/lib/python3.2/site-packages/zope.interface-4.0.5-py3.2-linux-i686.egg/zope/interface/adapter.py", line 601, in subscribers
[Thu Aug 07 13:41:42 2014] [error] [client 192.168.101.107]     subscription(*objects)
[Thu Aug 07 13:41:42 2014] [error] [client 192.168.101.107]   File "/var/lib/netprofile/np/lib/python3.2/site-packages/pyramid-1.5a2-py3.2.egg/pyramid/config/adapters.py", line 103, in derived_subscriber
[Thu Aug 07 13:41:42 2014] [error] [client 192.168.101.107]     return subscriber(arg[0])
[Thu Aug 07 13:41:42 2014] [error] [client 192.168.101.107]   File "/var/lib/netprofile/np/np/netprofile_core/netprofile_core/auth.py", line 229, in _auth_to_db
[Thu Aug 07 13:41:42 2014] [error] [client 192.168.101.107]     npsess = sess.query(NPSession).filter(NPSession.session_name == sname).one()
[Thu Aug 07 13:41:42 2014] [error] [client 192.168.101.107]   File "/var/lib/netprofile/np/lib/python3.2/site-packages/sqlalchemy/orm/query.py", line 2371, in one
[Thu Aug 07 13:41:42 2014] [error] [client 192.168.101.107]     "Multiple rows were found for one()")
[Thu Aug 07 13:41:42 2014] [error] [client 192.168.101.107] sqlalchemy.orm.exc.MultipleResultsFound: Multiple rows were found for one()
```

**Comment by unikmhz** [comment]
Does this still apply?
